namespace BetaSharp.Blocks;

public enum BlockRendererType: int
{
    Entity = -1,
    Standard = 0,
    Reed = 1,
    Torch = 2,
    Fire = 3,
    Fluids = 4,
    RedstoneWire = 5,
    Crops = 6,
    Door = 7,
    Ladder = 8,
    MinecartTrack = 9,
    Stairs = 10,
    Fence = 11,
    Lever = 12,
    Cactus = 13,
    Bed = 14,
    Repeater = 15,
    PistonBase = 16,
    PistonExtension = 17,
    Pane = 18,
    Vine = 20,
    FenceGate = 21,
    LilyPad = 23,
    Cauldron = 24,
    BrewingStand = 25,
    EndPortalFrame = 26,
    DragonEgg = 27,
    Cocoa = 28,
}
